ToDo.Web/Controllers/StatusController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ToDo.Business.Abstract;
using ToDo.Data;
using ToDo.Data.Repository.Shared.Absract;
using ToDo.Models;

namespace ToDo.Web.Controllers
{
    public class StatusController : Controller
    {
        private readonly IStatusService _statusService;

        public StatusController(IStatusService statusService)
        {
            _statusService = statusService;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Admin,User")]
        public IActionResult GetAll()
        {
            return Json(_statusService.GetAll());
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Add(Status status)
        {

            return Ok(_statusService.Add(status)); ;
        }


        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Update(Status status)
        {
           
            return Ok(_statusService.Update(status));                  
        }



        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Delete(Status status)
        {
           
            return Ok(_statusService.Delete(status.Id) );

        }

    }
}

ToDo.Web/Controllers/TagController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ToDo.Business.Abstract;
using ToDo.Data;
using ToDo.Data.Repository.Shared.Absract;
using ToDo.Models;
using ToDo.Models.ViewModels;

namespace ToDo.Web.Controllers
{
    [Authorize(Roles ="Admin")]
    public class TagController : Controller
    {
        private readonly ITagService _tagService;

     



        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            //1.yol
            //TagListVM vm = new TagListVM();
            //vm.Tags = _context.Tags.ToList();

            //return View(vm);

            //2.yol
            return View(new TagListVM { Tags = _tagService.GetAll().ToList()});
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
           _tagService.Delete(id);

            return RedirectToAction("Index");

        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult DeleteAjax(Tag tag)
        {
          
            return Ok(_tagService.Delete(tag.Id));

        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Add(Tag tag)
        {
           
            return Ok(_tagService.Add(tag).Id) ;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Update(int id )
        { 

            return View(_tagService.GetById(id));

        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Update(Tag tag) {
           
            return Ok(_tagService.Update(tag));
        
        }

        [Authorize(Roles = "Admin,User")]
        public IActionResult GetAll()
        {
            //data table için new diyerek isimsiz obje oluşturuyoruz
            return Json(new {data= _tagService.GetAll()});
        }
    }

    
}

ToDo.Web/Controllers/TodoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using ToDo.Business.Abstract;
using ToDo.Data;
using ToDo.Data.Repository.Absract;
using ToDo.Data.Repository.Shared.Absract;
using ToDo.Models;

namespace ToDo.Web.Controllers
{
    [Authorize]
    public class TodoController : Controller
    {
        private readonly ITodoService _todoService;

        public TodoController(ITodoService todoService)
        {
            _todoService = todoService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult GetAll()
        {         

            return Json(new { data = _todoService.GetAll(int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier))) });
        }

        public IActionResult RemoveTag(int todoId, int tagId)
        {
           

            return Ok(_todoService.RemoveTag(todoId,tagId));


        }


        [HttpPost]
        public IActionResult Add(Todo todo, int[] tags )
        {

           

            return Ok(_todoService.Add(todo, tags, int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier))));
        }

        //[HttpPost]
        //public IActionResult Delete(int todoId)
        //{
        //    _context.Todos.Remove(_context.Todos.Find(todoId));
        //    _context.SaveChanges();
        //    return Ok();
        //}

        [HttpPost]
        public IActionResult Delete(Todo todo)
        {
           
            return Ok(_todoService.Delete(todo.Id) is object);
        }


      













    }


}

ToDo.Web/Controllers/UserController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Security.Principal;
using ToDo.Business.Abstract;
using ToDo.Data;
using ToDo.Data.Repository.Absract;
using ToDo.Models;
using ToDo.Models.DTOs;
using ToDo.Models.ViewModels;

namespace ToDo.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        [Authorize(Roles ="Admin")]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public IActionResult GetAll()
        {
          
            return Json(new {data= _userService.GetAllWithTodoCount()});
        }


        [HttpPost]
        public async Task<IActionResult> Login(AppUser user)
        {
            ClaimsPrincipal? principal= _userService.CheckLogin(user);
            if (principal==null)
            {
                await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

                await HttpContext.SignInAsync(principal);
                return RedirectToAction("Index", "Home");
            }
            else
            {

              
            }

        }

        //public IActionResult RecoveryPassword()
        //{
        //    return View();  
        //}

        //[HttpPost]
        //public IActionResult ShowPassword(string name)
        //{
        //    AppUser user =_context.Users.FirstOrDefault(u=>u.Name==name);
        //    TempData["error"] = $"Kullanıcı Adı{user.Name} veya Şifreniz {user.Password}";
        //    return RedirectToAction("Login", "User");
        //}


        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Logout()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login");
        }


        //1.yöntem

        //public IActionResult Delete(int userId)
        //{
        //     _context.Users.Remove(_context.Users.Find(userId));
        //    _context.SaveChanges();
        //    return View();
        //}


        //2.yöntem

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Delete(AppUser appUser)
        {
            
            return Ok(_userService.Delete(appUser.Id));
        }



        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Add(AppUser appUser)
        {
         
            return Ok(_userService.Add(appUser));
        }

        [Authorize(Roles = "Admin")]   
        public IActionResult GetById(int id)
        {
            return Json(_userService.GetById(id));
            
        }


        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Update(AppUser appUser)
        {
          
            return Ok(_userService.Update(appUser));

        }

    }
}

ToDo.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ToDo.Web/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDo.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDo.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/2.0.7/css/dataTables.dataTables.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
          
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDo.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>


                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Tag" asp-action="Index">Etiketler</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Status" asp-action="Index">Durumlar</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="User" asp-action="Index">Kullanıcılar</a>
                            </li>
                        }


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Todo" asp-action="Index">Görevler</a>
                        </li>

                    </ul>
                    <div>Hoşgeldin, @User.FindFirst(ClaimTypes.GivenName).Value <a class="btn"  asp-action="Logout" asp-controller="User" >(Çıkış Yap)</a> </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ToDo.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/2.0.7/js/dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ToDo.Web/Views/Status/Index.cshtml
<div class="card">
    <div class="card-header bg-primary text-white text-center">Durumlar</div>
    <div class="card-body">
        <a href="#"  id="btnEkle" class="btn btn-success mb-3">Ekle</a>

        <table class="table table-bordered table-hover table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>İşlemler</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>



    </div>
    <div class="card-footer"></div>

</div>


<div class="modal fade" id="modalEkle" tabindex="-1" data-bs-backdrop="static"
     data-bs-keyboard="false"
     role="dialog"
     aria-labelledby="modalTitleId"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered modal-sm"
         role="document">
     
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalTitleId">
                        Yeni Durum Ekle
                    </h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">


                    <input type="text" id="txtStatusName"  class="form-control" placeholder="Lütfen durum adı giriniz" />
                                    </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"> Kapat </button>
                    <a href="#" id="btnSave" class="btn btn-primary"> Kaydet </a>
                </div>

      
    </div>
</div>
</div>



@section Scripts {
    <script>
        fillTable();

        $("#btnEkle").click(function () {
            $("#modalEkle").modal("show");
            $("#btnSave").text("Kaydet").removeClass("btn-success").addClass("btn-primary").off().click(kaydet);
            $("#txtStatusName").val("");
        });


        $("#btnSave").click(kaydet);

        function kaydet () {
            let statusName = $("#txtStatusName").val();
            $.ajax({
                url: '/Status/Add',
                type: 'POST',
                data: { name: statusName },
                success: function (res) {
                    console.log(res);

                    $("#modalEkle").modal('hide');
                    $("#txtStatusName").val("");
                    $("tbody").append(`
                                                    <tr>
                                                        <td>${res.id}</td>
                                                                 <td>${statusName}</td>
                                                         <td><a onclick="deleteStatus(${res},this)" href="#" class="btn btn-danger">Sil</a>
                                                                          <a onclick="updateStatus(${res.id},this,'${statusName}')" href="#" class="btn btn-warning">Düzenle</a>
                                                         </td>
                                                    </tr>

                                                    `);


                }
            });
        }


        function deleteStatus(id,element) { 
            
            if (confirm("Silmek istediğinizden emin misiniz ?")) { 
            
            $.ajax({
                url:'/Status/Delete',
                type:'POST',
                data: {id:id},
                success: function () {
                    $(element).parent().parent().remove();

                }

            });
            
            }
            
        }

        function updateStatus(id, element,statusName) {
            $("#modalEkle").modal('show');
            $("#txtStatusName").val(statusName);
            $("#btnSave").text("Güncelle").removeClass("btn-primary").addClass("btn-success").off().click(function () {
                $.ajax({
                    url:'/Status/Update',
                    type:'POST',
                    data: { id: id, name: $("#txtStatusName").val() },
                    success: function () {
                        $("#modalEkle").modal("hide");
                        $(element).parent().parent().children()[1].innerText = $("#txtStatusName").val();

                       
                    }
                })
            });

        }


        function fillTable() {
            $.ajax({
                url: '/Status/GetAll',
                type: 'GET',
                success: function (res) {
                    $("tbody").empty();
                    for (let item of res) {
                        $("tbody").append(`
                                    <tr>
                                        <td>${item.id}</td>
                                                 <td ondblclick="updateStatusInline(${item.id},this)">${item.name}</td>
                                                 <td>
                                      <a onclick="deleteStatus(${item.id},this)" href="#" class="btn btn-danger">Sil</a> 
                                    <a onclick="updateStatus(${item.id},this,'${item.name}')" href="#" class="btn btn-warning">Düzenle</a></td>
                                    </tr>

                                    `);
                    }

                }
            });
        }

        function updateStatusInline(element) {
            $(element).attr("contentEditable", "true");
            $(element).one().focusout(function () {

                $(element).removeAttr("contentEditable", "true");
                $.ajax({
                    url:'/Status/Update',
                    type:'POST',
                    data: {id:id,name:$(element).text()},
                    success: function (res) {

                    }
                })
            });
        }
        






    </script>
}

ToDo.Web/Views/Tag/Index.cshtml
<div class="card">
    <div class="card-header bg-warning text-center fs-4">Etiket Listesi</div>
    <div class="card-body">
        <a href="#" id="btnEkle" class="btn btn-success" >Ekle</a>

        <table class="table table-bordered table-hover table-striped">
        </table>

    </div>
    <div class="card-footer"> </div>




</div>



<div class="modal fade" id="modalEkle" tabindex="-1" data-bs-backdrop="static"
     data-bs-keyboard="false"
     role="dialog"
     aria-labelledby="modalTitleId"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered modal-sm"
         role="document">
      
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalTitleId">
                        Yeni Etiket Ekle
                    </h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">


                    <input id="txtTagName"  class="form-control" placeholder="Lütfen etiket adı giriniz" />


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"> Kapat </button>
                    <a id="btnSave" class="btn btn-primary"> Kaydet </a>
                </div>

       
    </div>
</div>


@section Scripts {
    <script>
        //bonus
            $("#modalEkle").on('shown.bs.modal', function () {
                $(this).find('#txtTagName').focus().val('');
            });

        $("#btnEkle").click(function () {
            $("#modalEkle").modal("show");
            $("#btnSave").off().click(function () {

                $.ajax({
                    url: '/Tag/Add',
                    type: 'POST',
                    data: {
                            name: $("#txtTagName").val()
                    },
                    success: function (res) {
                            $("#modalEkle").modal("hide");
                        
                       // DataTable.ajax.reload();
                          DataTable.row.add({ id: res, name: $("#txtTagName").val() }).draw();

                    }
                });

            });


           
        })



        var DataTable = $("table").DataTable({
            ajax: '/Tag/GetAll',
            columns: [
                { data: 'id', title: 'ID' },
                { data: 'name', title: 'Etiket Adı' },
                {
                    data: 'id', title: 'İşlemler', render: function (data, type, row) {

                            return `<a id="btnSil-${data}" onclick="deleteTag(${data},this)" hidden class="btn satir-${data} btn-danger">Sil</a>
                                                        <a onclick="updateTag(${data},this)" class="btn btn-success ">Düzenle</a>
                                                        <a id="btnKaydet-${data}" class="btn btn-warning satir-${data}" hidden>Kaydet</a>
                                            <a id="btnIptal-${data}" class="btn btn-danger satir-${data}" hidden>İptal</a>
                        `;

                    }
                }
            ],
            language: {
                    url: '//cdn.datatables.net/plug-ins/2.0.7/i18n/tr.json',
                    deleteTag:"Kayıt bulunamadı"
            }
               
        });


        function deleteTag(id, element) {

            if (confirm("Emin misiniz?")) {
                $.ajax({
                    url: '/Tag/DeleteAjax',
                    type: 'POST',
                    data: { id: id },
                    success: function () {
                        //  DataTable.ajax.reload();
                        let satir = $(element).parent().parent();
                        DataTable.row(satir).remove().draw();
                    }
                });
            }


        }

        function updateTag(id, button) {

            let td = $($(button).parent().parent().children()[1]);

            $(".satir-" + id).removeAttr("hidden").show();
             
            $(button).hide();


           let eskiDeger = td.text();

            td.attr("contentEditable", "true").focus();


            $("#btnIptal-" + id).off().click(function () {
                td.text(eskiDeger);
                td.removeAttr("contentEditable");
                $(button).show();
                $(".satir-" + id).hide();
             

            });


                $("#btnKaydet-" + id).off().click(function () {
                $.ajax({
                    url:'/Tag/Update',
                    type:'POST',
                    data: {id:id,name:td.text()},
                    success: function () {
                        td.removeAttr("contentEditable");
                        $(button).show();
                        $(".satir-" + id).hide();
                        

                    }
                });
            });







        
        }

    </script>
}

ToDo.Web/Views/Tag/Update.cshtml
@model Tag

<form method="post" asp-action="Update">
    <input  asp-for="Id" hidden/>
    <input asp-for="Name" class="form-control" />

    <button type="submit" class="btn btn-primary"> Kaydet</button>
</form>

ToDo.Web/Views/Todo/Index.cshtml
<div class="card">
    <div class="card-header bg-primary text-white text-center">Todo Listesi</div>
    <div class="card-body">
        <a href="#" class="btn btn-primary" id="btnAdd">Ekle</a>
        <table class="table table-bordered table-striped table-hover">
        </table>
    </div>
</div>

<div class="modal fade" id="modalEkle" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false" role="dialog" aria-labelledby="modalTitleId" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitleId">
                    Yeni Görev Ekle
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <div class="mb-3 row">
                    <input id="txtTitle" type="text" class="form-control" placeholder="Lütfen etiket adı giriniz" />
                </div>
                <div class="mb-3 row">
                    <textarea rows="3" id="txtDescription" class="form-control" placeholder="Lütfen etiket adı giriniz"></textarea>
                </div>

                <div class="mb-3 row">
                    <select id="ddlStatus" class="form-select"></select>
                </div>
                <div class="mb-3 row">
                    <select id="ddlTag" multiple class="form-select"></select>
                </div>




            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"> Kapat </button>
                <a id="btnSave" class="btn btn-primary"> Kaydet </a>
            </div>


        </div>
    </div>
</div>

@section Scripts {
    <script>
        var DataTable;
        $(document).ready(function () {

            $("#btnAdd").click(function () {
                $("#modalEkle").modal("show");
                fillDdlStatus();
                fillDdlTag();
                $("#btnSave").off().click(function () {

                    $.ajax({
                        url: '/Todo/Add',
                        type: 'POST',
                        data: {
                            todo: {
                                name: $("#txtTitle").val(),
                                description: $("#txtDescription").val(),
                                statusId: $("#ddlStatus").val()
                            },
                            tags: $("#ddlTag").val()


                        },
                        success: function (res) {
                            $("#modalEkle").modal("hide");
                            //  DataTable.row.add(res).draw();
                            DataTable.ajax.reload();
                        }
                    });

                });


            });
            DataTable = $("table").DataTable({
                ajax: '/Todo/GetAll',
                columns: [
                    { data: 'id', title: 'ID' },
                    { data: 'name', title: 'Başlık' },
                    { data: 'description', title: 'Açıklama' },
                    { data: 'status.name', title: 'Durum' },
                    {
                        data: 'tags', title: 'Etiketler', render: function (data, type, row) {

                            let etiketler = "";
                            for (let item of data) {
                                etiketler += `<div><span class="bg-warning text-dark rounded-pill">${item.name}</span>
                                                                    <a href="#" onclick="removeTag(${row.id},this,${item.id})" class="btn btn-sm btn-danger">x</a></div>`;
                            }
                            return etiketler;

                        }
                    },
                    {
                        data: 'id', title: 'İşlemler', render: function (data) {
                            return `<a href="#" class="btn btn-success btn-sm" onclick="updateTodo(${data})">Düzenle</a> <a href="#" class="btn btn-danger btn-sm" onclick="deleteTodo(${data},this)">Sil</a>`
                        }
                    }
                ]
            });


        });

        function updateTodo(todoId) {

            $("#modalEkle").modal("show");

            $.ajax({
                type: "get",
                url: "/Todo/UpdateTodo/",
                data: {
                    id: todoId,
                },
                success: function (res) {

                    $("#txtTitle").val(res.name);
                    $("#txtDescription").val(res.description);

                    fillDdlStatus(res.status.id);
                    fillDdlTag(res.tags);
                }
            })
            $("#btnSave").off().click(function () {
                let todo = {
                    id: todoId,
                    name: $("#txtTitle").val(),
                    description: $("#txtDescription").val(),
                    statusId: $("#ddlStatus").val()
                }
                $.ajax({
                    type: "post",
                    url: "/Todo/UpdateTodo/",
                    data: {
                        todo: todo,
                        tagsId: $("#ddlTag").val(),


                    },
                    success: function () {
                        $("#modalEkle").modal("hide");
                        DataTable.ajax.reload();
                    }
                })
            })



        }

        function fillDdlStatus(statusId) {
            $.ajax({
                url: '/Status/GetAll',
                type: 'GET',
                success: function (res) {
                    $("#ddlStatus").empty();
                    $("#ddlStatus").append(new Option("Lütfen bir durum seçiniz", 0));
                    for (let item of res) {
                        $("#ddlStatus").append(new Option(item.name, item.id, false, item.id == statusId))
                    }

                    $("#ddlStatus").select2({
                        dropdownParent: $("#modalEkle"),
                        width: "100%"
                    })

                }
            });
        }

        function fillDdlTag(tagsList) {
            $.ajax({
                url: '/Tag/GetAll',
                type: 'GET',
                success: function (res) {
                    $("#ddlTag").empty();

                    for (let item of res.data) {
                        $("#ddlTag").append(new Option(item.name, item.id, false, tagsList.find(t => t.id == item.id) != null));

                    }

                    $("#ddlTag").select2({
                        dropdownParent: $("#modalEkle"),
                        width: "100%",
                        placeholder: "Lütfen Etiket Seçiniz!"
                    })

                }
            });


        }





        function removeTag(todoId, button, tagId) {

            $.ajax({
                url: '/Todo/RemoveTag',
                type: 'POST',
                data: {
                    todoId: todoId,
                    tagId: tagId
                },
                success: function () {
                    $(button).parent().remove();
                }
            });

        }

        function deleteTodo(todoId, button) {

            $.ajax({
                url: '/Todo/Delete',
                type: 'POST',
                data: {
                    todo: {
                        id: todoId
                    }
                },
                success: function () {
                    let satir = $(button).parent().parent();
                    DataTable.row(satir).remove().draw();
                    //    DataTable.ajax.reload();
                }
            });

        }


    </script>
}